services:
- docker
script:
- VERSION=1.0.$(date +"%m%d")
- echo "Building and Pushing ${DOCKER_IMAGE}:${VERSION} using ${DOCKER_FILE} to ${DOCKER_REGISTRY}"
- docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} ${DOCKER_REGISTRY}
- docker build -t "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${VERSION}" -f ${DOCKER_FILE} .
- docker tag ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${VERSION} ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:latest
- docker push ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${VERSION}
- docker push ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:latest
env:
  global:
  - DOCKER_REGISTRY=docker.io
  - DOCKER_IMAGE=lockerua/ftp-encrypted-storage
  - DOCKER_FILE=Dockerfile
